//#include "debounced_digital_in.h"
#include "BT817Q.hpp"
#include "CANbus.h" //generated by dbcc, you also must have the dbcc file formated correctly
#include "dash_screen.hpp"
#include "mbed.h"
#include "pin_config.hpp"
#include "vehicle_state.hpp"
// I had to move these lines
// BA_DEF_ "BusType" STRING ;
// BA_DEF_DEF_ "BusType" "";
// BA_ "BusType" "CAN";
// Below the BO_

DashScreen screen{
    PIN_MOSI, PIN_MISO, PIN_SCK, PIN_CS, PIN_PDN, PIN_IRQ, EvePresets::CFAF800480H0
};
CAN can{PIN_CAN_RX, PIN_CAN_TX, CAN_FREQUENCY};
CANMessage msg;
DigitalIn layoutBtn{PIN_LAYOUT};
bool lastLayoutBtnState;
//DebouncedDigitalIn debouncedLayoutBtn{layoutBtn, 5};
uint8_t currentScreen = 0;
EventQueue queue = EventQueue{EVENTS_EVENT_SIZE * 32};
AnalogIn driveDial{PIN_MODE};
AnalogIn tractionDial{PIN_TC};
AnalogIn regenDial{PIN_REGEN};
uint8_t driveState;
uint8_t tractionState;
uint8_t regenState;

// CAN message structure generated by dbcc
// dbcc {dbcFileName.dbc}
// Also used a python function to generate the decoding stuff
// Our dbc file is a bit weird, the extended CAN id's need to have a 1 in the MSB
// These Need to Come after BO
// BA_DEF_ "BusType" STRING ;
// BA_DEF_DEF_ "BusType" "";
// BA_ "BusType" "CAN";
can_obj_canbus_h_t g_dbcc_state;
VehicleState vsm_state;
static int tick = 0;
uint32_t lastFrame = 0;
uint32_t curFrame = 0;
uint16_t fps = 0;

int main() {
    printf("Hello World!!\n");
    // while(true)
    // {
    //     printf("hi");
    // }
    screen.init(EvePresets::CFAF800480H0);
    screen.setRotate(1); //Inverted Landscape since dash is mounted upsidedown
    // debouncedLayoutBtn.set_valid_read_count(7);
    can.attach(&canISR, CAN::RxIrq); // callback function to handle CAN interrupts
    queue.call_every(10ms, &readLayoutButton);
    queue.call_every(10ms, &readDials);
    queue.call_every(10ms, &drawScreenLayout);
    queue.call_every(100ms, []() { tick++; }); //Lambda expression to increase ticks every 100ms, or I hope it runs every 100ms
    queue.call_every(1s, &readFPS);
    queue.dispatch_forever();
    return 0;
}

/**
 * @brief Function to read button state and cycles through possible layouts on button press
 * These are the what values correspond to what screen
 */
void readLayoutButton() {
    // const bool debounced_button_state = debouncedLayoutBtn.read();
    const bool debounced_button_state = layoutBtn.read();
    if (debounced_button_state && !lastLayoutBtnState) {
        currentScreen = (currentScreen >= 4) ? 0 : (currentScreen + 1);
        printf("Current Screen: %d", currentScreen);
    }
    lastLayoutBtnState = debounced_button_state;
}

/**
 * @brief Function to read dial state
 *  3.3V, 2.2V, 1.1V, GND
 *  Not sure how jiterry these readings
 *  I can compare floats or just cast it to an int
 */
void readDials() {
    // 0 - 3.3V
    // 0 - 4096, each volt is 1241
    // ADC is 12 Bits ADC12_IN1
    uint16_t rawDriveVal = driveDial.read_u16() >> 4;
    if (rawDriveVal >= 3351) driveState = 2; // > 2.7V
    else if (rawDriveVal >= 2110)
        driveState = 1; // > 1.7V
    else if (rawDriveVal >= 744)
        driveState = 0; // > 0.6V
    else
        driveState = 0; // ground, idk what to do here

    uint16_t rawTractionVal = tractionDial.read_u16() >> 4;
    if (rawTractionVal >= 3351) tractionState = 2; // > 2.7V
    else if (rawTractionVal >= 2110)
        tractionState = 1; // > 1.7V
    else if (rawTractionVal >= 744)
        tractionState = 0; // > 0.6V
    else
        tractionState = 0; // ground

    uint16_t rawRegenVal = regenDial.read_u16() >> 4;
    if (rawRegenVal >= 3351) regenState = 3; // > 2.7V
    else if (rawRegenVal >= 2110)
        regenState = 2; // > 1.7V
    else if (rawRegenVal >= 744)
        regenState = 1; // > 0.6V
    else
        regenState = 0; // ground

    // between above 3, above 2 <3,

    // Send the CAN Message
    printf("Drive State: %d\n", driveState);
    printf("Traction Sate: %d\n", tractionState);
    printf("Regen Stae: %d\n", regenState);
    sendCANMessage();
}

/**
 * @brief Function to draw screen layout
 * Layouts depend on currentScreen
 * 0: main
 * 1: Thermal
 * 2: CellTemps
 * 3: CellVolts
 * 4: Fault
 */
void drawScreenLayout() {
    // Render the screen like how it was done before?
    // Should look into optimal ways of doing this
    // Also add fps overlay to the screens
    // Also might need to edit screen layouts since stuff seems to have been changed

    switch (currentScreen) {
    case 0:
        screen.drawMainDisplay(
            vsm_state.batt_status_shutdown_final,
            vsm_state.sme_temp_faultlevel > 0 && vsm_state.sme_temp_faultlevel < 4,
            vsm_state.vcu_etc_ready_to_drive,
            vsm_state.vcu_etc_batt_precharge_done,
            true /*fans*/,
            vsm_state.batt_power_pack_voltage,
            vsm_state.batt_stat_high_cell_temp,
            vsm_state.batt_power_soc,
            tick,
            vsm_state.sme_trqspd_speed,
            "lap", // laptime
            vsm_state.batt_status_glv_voltage,
            vsm_state.sme_temp_motortemperature,
            vsm_state.sme_temp_controllertemperature,
            vsm_state.sme_temp_dc_bus_v,
            regenState
        );
        printf("In Main Display \n");
        break;
    case 1: {
        //Lambda expression to take the average temps
        auto avgTireTemps = [](const uint8_t temps[8]) -> float {
            uint16_t sum = 0;
            for (int i = 0; i < 8; i++)
                sum += temps[i];
            return sum / 8.0f;
        };
        screen.drawThermalScreen(
            vsm_state.batt_stat_high_cell_temp,
            vsm_state.sme_temp_motortemperature,
            vsm_state.sme_temp_controllertemperature,
            avgTireTemps(vsm_state.tperiph_fl_tire_temps), (float)vsm_state.tperiph_fl_side_temp,
            avgTireTemps(vsm_state.tperiph_fr_tire_temps), (float)vsm_state.tperiph_fr_side_temp,
            avgTireTemps(vsm_state.tperiph_bl_tire_temps), (float)vsm_state.tperiph_bl_side_temp,
            avgTireTemps(vsm_state.tperiph_br_tire_temps), (float)vsm_state.tperiph_br_side_temp,
            vsm_state.izze_brake_fl, vsm_state.izze_brake_fr,
            vsm_state.izze_brake_rl, vsm_state.izze_brake_rr,
            (float)vsm_state.vcu_etc_brake_pressure_front,
            (float)vsm_state.vcu_etc_brake_pressure_rear
        );
        break;
    }
    case 2:
        screen.debugCellTemps(vsm_state.batt_mod_temps_A, vsm_state.batt_mod_temps_B);
        break;
    case 3:
        screen.debugCellVolts(vsm_state.batt_mod_volts);
        break;
    case 4:
        printf("In Faults Display \n");
        screen.drawDebugFaultLayout(
            vsm_state.batt_status_bms_fault,
            vsm_state.batt_status_imd_fault,
            vsm_state.batt_status_shutdown_out,
            vsm_state.batt_status_precharge_done,
            vsm_state.batt_status_precharging,
            vsm_state.batt_status_charging,
            vsm_state.batt_power_pack_voltage,
            vsm_state.batt_status_glv_voltage,
            vsm_state.batt_status_fault_index,
            vsm_state.vcu_etc_ready_to_drive,
            (vsm_state.vcu_etc_implausibility_apps_out_of_range | vsm_state.vcu_etc_implausibility_bpps_out_of_range | vsm_state.vcu_etc_implausibility_apps_deviation | vsm_state.vcu_etc_implausibility_bse_out_of_range | vsm_state.vcu_etc_implausibility_brake_and_accel), // lot of implausbility options now
            vsm_state.vcu_etc_batt_precharge_done,
            vsm_state.vcu_etc_brake_pedal_travel,
            vsm_state.vcu_etc_bpps_he,
            vsm_state.sme_trqspd_controller_overtermp,
            vsm_state.sme_trqspd_running,
            vsm_state.sme_trqspd_powering_enabled,
            vsm_state.sme_trqspd_powering_ready,
            vsm_state.sme_temp_motortemperature,
            vsm_state.sme_temp_faultcode,
            vsm_state.sme_temp_faultlevel,
            tick
        );
        break;
    }
}
/**
 * @brief Called when there is an incomming CAN message from interrupt
 *  Just adds the decoding process to the queue
 */
void canISR() {
    queue.call(processCANMessage);
}
/**
 * @brief Decoding the CAN message receieved
 * Worried about if the eventQueue is busy with other tasks and the original message is missed
 * Not sure how long the other tasks take and the maximum time between messages
 * Entirely generated by a python script although I had to manually uncomment the data that was used
 * I originally thought CAN dbcc provided automatic scaling, it provides the automatic packaging and unpacking of CAN Messages 
 *
 */
void processCANMessage() {
    while (can.read(msg)) {
        switch (msg.id) {
        case 0x192:   // VCU_TPDO_PEDAL_TRAVEL (BPPS_HE, brake pedal travel)
        case 0x193:   // VCU_TPDO_STATUS (RTD, precharge, brake pressures, implausibilities)
        case 0x482:   // SME_TPDO_Torque_speed
        case 0x682:   // SME_TPDO_Temperature
        case 0x391:   // BATT_TPDO_STATUS
        case 0x392:   // BATT_TPDO_POWER
        case 0x393:   // BATT_TPDO_CELL_STATS
        case 0xa0001: // VDM_GPS_DATA
        case 0x1a5:   // TPERIPH_FL_TPDO_DATA
        case 0x1a6:   // TPERIPH_FR_TPDO_DATA
        case 0x1a7:   // TPERIPH_BL_TPDO_DATA
        case 0x1a8:   // TPERIPH_BR_TPDO_DATA
        case 0x2a5:   // TPERIPH_FL_TPDO_TIRETEMP
        case 0x2a6:   // TPERIPH_FR_TPDO_TIRETEMP
        case 0x2a7:   // TPERIPH_BL_TPDO_TIRETEMP
        case 0x2a8:   // TPERIPH_BR_TPDO_TIRETEMP
        case 0x494:   // BATT_TPDO_MOD0_VOLTS
        case 0x497:   // BATT_TPDO_MOD1_VOLTS
        case 0x49a:   // BATT_TPDO_MOD2_VOLTS
        case 0x49d:   // BATT_TPDO_MOD3_VOLTS
        case 0x4a0:   // BATT_TPDO_MOD4_VOLTS
        case 0x495:   // BATT_TPDO_MOD0_TEMPS_A
        case 0x496:   // BATT_TPDO_MOD0_TEMPS_B (cells 6-11, unused by display)
        case 0x498:   // BATT_TPDO_MOD1_TEMPS_A
        case 0x499:   // BATT_TPDO_MOD1_TEMPS_B
        case 0x49b:   // BATT_TPDO_MOD2_TEMPS_A
        case 0x49c:   // BATT_TPDO_MOD2_TEMPS_B
        case 0x49e:   // BATT_TPDO_MOD3_TEMPS_A
        case 0x49f:   // BATT_TPDO_MOD3_TEMPS_B
        case 0x4a1:   // BATT_TPDO_MOD4_TEMPS_A
        case 0x4a2:   // BATT_TPDO_MOD4_TEMPS_B
        case 0x4c4:   // IZZE_BRAKETEMP_S1M1 (CH1-4)
        case 0x4c5:   // IZZE_BRAKETEMP_S1M2 (CH5-8)
        case 0x4c6:   // IZZE_BRAKETEMP_S1M3 (CH9-12)
        case 0x4c7:   // IZZE_BRAKETEMP_S1M4 (CH13-16)
        {
            printf("reading from CAN\n");
            uint64_t payload = 0;
            memcpy(&payload, msg.data, msg.len);
            unpack_message(&g_dbcc_state, msg.id, payload, msg.len, 0);

            if (false) {
            } else if (msg.id == 0x192) { // VCU_TPDO_PEDAL_TRAVEL
                auto& t = g_dbcc_state.can_0x192_VCU_TPDO_PEDAL_TRAVEL;
                vsm_state.vcu_etc_bpps_he = (uint8_t)t.VCU_BPPS_HE;
                vsm_state.vcu_etc_brake_pedal_travel = t.VCU_BRAKE_PEDAL_TRAVEL;
                // vsm_state.vcu_etc_accel_pedal_travel = t.VCU_ACCEL_PEDAL_TRAVEL;
            } else if (msg.id == 0x193) { // VCU_TPDO_STATUS
                auto& t = g_dbcc_state.can_0x193_VCU_TPDO_STATUS;
                vsm_state.vcu_etc_brake_pressure_front = t.VCU_BRAKE_PRESSSURE_FRONT;
                vsm_state.vcu_etc_brake_pressure_rear = t.VCU_BRAKE_PRESSSURE_REAR;
                vsm_state.vcu_etc_ready_to_drive = t.VCU_ETC_READY_TO_DRIVE;
                vsm_state.vcu_etc_batt_precharge_done = t.VCU_ETC_BATT_PRECHARGE_DONE;
                vsm_state.vcu_etc_implausibility_apps_out_of_range = t.VCU_ETC_IMPLAUS_APPS_OUT_OF_RANGE;
                vsm_state.vcu_etc_implausibility_bpps_out_of_range = t.VCU_ETC_IMPLAUS_BPPS_OUT_OF_RANGE;
                vsm_state.vcu_etc_implausibility_apps_deviation = t.VCU_ETC_IMPLAUS_APPS_DEVIATION;
                vsm_state.vcu_etc_implausibility_bse_out_of_range = t.VCU_ETC_IMPLAUS_BSE_OUT_OF_RANGE;
                vsm_state.vcu_etc_implausibility_brake_and_accel = t.VCU_ETC_IMPLAUS_BRAKE_AND_ACCEL;
                // vsm_state.vcu_etc_motor_enabled      = t.VCU_ETC_MOTOR_ENABLED;
                // vsm_state.vcu_etc_reverse            = t.VCU_ETC_REVERSE;
                // vsm_state.vcu_etc_brakelight         = t.VCU_ETC_BRAKELIGHT;
            } else if (msg.id == 0x482) { // SME_TPDO_Torque_speed
                auto& t = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed;
                vsm_state.sme_trqspd_speed = t.SME_TRQSPD_Speed;
                vsm_state.sme_trqspd_controller_overtermp = t.SME_TRQSPD_Controller_Overtermp;
                vsm_state.sme_trqspd_running = t.SME_TRQSPD_Running;
                vsm_state.sme_trqspd_powering_enabled = t.SME_TRQSPD_Powering_Enabled;
                vsm_state.sme_trqspd_powering_ready = t.SME_TRQSPD_Powering_Ready;
                // vsm_state.sme_trqspd_torque          = t.SME_TRQSPD_Torque;
                // vsm_state.sme_trqspd_reverse         = t.SME_TRQSPD_Reverse;
                // vsm_state.sme_trqspd_forward         = t.SME_TRQSPD_Forward;
            } else if (msg.id == 0x682) { // SME_TPDO_Temperature
                // raw values have offset -40; subtract to get actual °C
                auto& t = g_dbcc_state.can_0x682_SME_TPDO_Temperature;
                uint8_t raw_mtr = t.SME_TEMP_MotorTemperature;
                uint8_t raw_ctrl = t.SME_TEMP_ControllerTemperature;
                vsm_state.sme_temp_motortemperature = (raw_mtr >= 40) ? (uint8_t)(raw_mtr - 40) : 0;
                vsm_state.sme_temp_controllertemperature = (raw_ctrl >= 40) ? (uint8_t)(raw_ctrl - 40) : 0;
                vsm_state.sme_temp_dc_bus_v = t.SME_TEMP_DC_Bus_V;
                vsm_state.sme_temp_faultcode = t.SME_TEMP_FaultCode;
                vsm_state.sme_temp_faultlevel = t.SME_TEMP_FaultLevel;
                // vsm_state.sme_temp_buscurrent = t.SME_TEMP_BusCurrent;
            } else if (msg.id == 0x391) { // BATT_TPDO_STATUS
                auto& t = g_dbcc_state.can_0x391_BATT_TPDO_STATUS;
                vsm_state.batt_status_bms_fault = t.BATT_STATUS_BMS_FAULT;
                vsm_state.batt_status_imd_fault = t.BATT_STATUS_IMD_FAULT;
                vsm_state.batt_status_shutdown_final = t.BATT_STATUS_SHUTDOWN_FINAL;
                vsm_state.batt_status_shutdown_out = t.BATT_STATUS_SHUTDOWN_OUT;
                vsm_state.batt_status_precharging = t.BATT_STATUS_PRECHARGING;
                vsm_state.batt_status_precharge_done = t.BATT_STATUS_PRECHARGE_DONE;
                vsm_state.batt_status_charging = t.BATT_STATUS_CHARGING;
                vsm_state.batt_status_fault_index = t.BATT_STATUS_FAULT_INDEX;
                vsm_state.batt_status_glv_voltage = t.BATT_STATUS_GLV_VOLTAGE;
                // vsm_state.batt_status_shutdown_in  = t.BATT_STATUS_SHUTDOWN_IN;
                // vsm_state.batt_status_balancing    = t.BATT_STATUS_BALANCING;
                // vsm_state.batt_status_fan_pwm_duty = t.BATT_STATUS_FAN_PWM_DUTY;
            } else if (msg.id == 0x392) { // BATT_TPDO_POWER
                auto& t = g_dbcc_state.can_0x392_BATT_TPDO_POWER;
                vsm_state.batt_power_pack_voltage = t.BATT_POWER_PACK_VOLTAGE;
                // raw SOC has 0.1 scaling (0–1000 = 0–100%); divide by 10
                vsm_state.batt_power_soc = (uint8_t)(t.BATT_POWER_SOC / 10);
                // vsm_state.batt_power_current             = t.BATT_POWER_CURRENT;
                // vsm_state.batt_power_instantaneous_power = t.BATT_POWER_INSTANTANEOUS_POWER;
            } else if (msg.id == 0x393) { // BATT_TPDO_CELL_STATS
                // raw has 0.2 scaling, divide by 5 to get °C
                vsm_state.batt_stat_high_cell_temp = (uint8_t)(g_dbcc_state.can_0x393_BATT_TPDO_CELL_STATS.BATT_STAT_HIGH_CELL_TEMP / 5);
            } else if (msg.id == 0xa0001) { // VDM_GPS_DATA
                vsm_state.vdm_gps_speed = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_SPEED;
                // vsm_state.vdm_gps_altitude          = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_ALTITUDE;
                // vsm_state.vdm_gps_true_course       = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_TRUE_COURSE;
                // vsm_state.vdm_gps_satellites_in_use = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_SATELLITES_IN_USE;
            }
            // Tire peripheral side temps
            else if (msg.id == 0x1a5) {
                vsm_state.tperiph_fl_side_temp = g_dbcc_state.can_0x1a5_TPERIPH_FL_TPDO_DATA.TPERIPH_FL_DATA_SIDE_TIRE_TEMP;
            } else if (msg.id == 0x1a6) {
                vsm_state.tperiph_fr_side_temp = g_dbcc_state.can_0x1a6_TPERIPH_FR_TPDO_DATA.TPERIPH_FR_DATA_SIDE_TIRE_TEMP;
            } else if (msg.id == 0x1a7) {
                vsm_state.tperiph_bl_side_temp = g_dbcc_state.can_0x1a7_TPERIPH_BL_TPDO_DATA.TPERIPH_BL_DATA_SIDE_TIRE_TEMP;
            } else if (msg.id == 0x1a8) {
                vsm_state.tperiph_br_side_temp = g_dbcc_state.can_0x1a8_TPERIPH_BR_TPDO_DATA.TPERIPH_BR_DATA_SIDE_TIRE_TEMP;
            }
            // Tire surface temps (8 pixels per corner)
            else if (msg.id == 0x2a5) {
                auto& t = g_dbcc_state.can_0x2a5_TPERIPH_FL_TPDO_TIRETEMP;
                vsm_state.tperiph_fl_tire_temps[0] = t.TPERIPH_FL_TIRETEMP_1;
                vsm_state.tperiph_fl_tire_temps[1] = t.TPERIPH_FL_TIRETEMP_2;
                vsm_state.tperiph_fl_tire_temps[2] = t.TPERIPH_FL_TIRETEMP_3;
                vsm_state.tperiph_fl_tire_temps[3] = t.TPERIPH_FL_TIRETEMP_4;
                vsm_state.tperiph_fl_tire_temps[4] = t.TPERIPH_FL_TIRETEMP_5;
                vsm_state.tperiph_fl_tire_temps[5] = t.TPERIPH_FL_TIRETEMP_6;
                vsm_state.tperiph_fl_tire_temps[6] = t.TPERIPH_FL_TIRETEMP_7;
                vsm_state.tperiph_fl_tire_temps[7] = t.TPERIPH_FL_TIRETEMP_8;
            } else if (msg.id == 0x2a6) {
                auto& t = g_dbcc_state.can_0x2a6_TPERIPH_FR_TPDO_TIRETEMP;
                vsm_state.tperiph_fr_tire_temps[0] = t.TPERIPH_FR_TIRETEMP_1;
                vsm_state.tperiph_fr_tire_temps[1] = t.TPERIPH_FR_TIRETEMP_2;
                vsm_state.tperiph_fr_tire_temps[2] = t.TPERIPH_FR_TIRETEMP_3;
                vsm_state.tperiph_fr_tire_temps[3] = t.TPERIPH_FR_TIRETEMP_4;
                vsm_state.tperiph_fr_tire_temps[4] = t.TPERIPH_FR_TIRETEMP_5;
                vsm_state.tperiph_fr_tire_temps[5] = t.TPERIPH_FR_TIRETEMP_6;
                vsm_state.tperiph_fr_tire_temps[6] = t.TPERIPH_FR_TIRETEMP_7;
                vsm_state.tperiph_fr_tire_temps[7] = t.TPERIPH_FR_TIRETEMP_8;
            } else if (msg.id == 0x2a7) {
                auto& t = g_dbcc_state.can_0x2a7_TPERIPH_BL_TPDO_TIRETEMP;
                vsm_state.tperiph_bl_tire_temps[0] = t.TPERIPH_BL_TIRETEMP_1;
                vsm_state.tperiph_bl_tire_temps[1] = t.TPERIPH_BL_TIRETEMP_2;
                vsm_state.tperiph_bl_tire_temps[2] = t.TPERIPH_BL_TIRETEMP_3;
                vsm_state.tperiph_bl_tire_temps[3] = t.TPERIPH_BL_TIRETEMP_4;
                vsm_state.tperiph_bl_tire_temps[4] = t.TPERIPH_BL_TIRETEMP_5;
                vsm_state.tperiph_bl_tire_temps[5] = t.TPERIPH_BL_TIRETEMP_6;
                vsm_state.tperiph_bl_tire_temps[6] = t.TPERIPH_BL_TIRETEMP_7;
                vsm_state.tperiph_bl_tire_temps[7] = t.TPERIPH_BL_TIRETEMP_8;
            } else if (msg.id == 0x2a8) {
                auto& t = g_dbcc_state.can_0x2a8_TPERIPH_BR_TPDO_TIRETEMP;
                vsm_state.tperiph_br_tire_temps[0] = t.TPERIPH_BR_TIRETEMP_1;
                vsm_state.tperiph_br_tire_temps[1] = t.TPERIPH_BR_TIRETEMP_2;
                vsm_state.tperiph_br_tire_temps[2] = t.TPERIPH_BR_TIRETEMP_3;
                vsm_state.tperiph_br_tire_temps[3] = t.TPERIPH_BR_TIRETEMP_4;
                vsm_state.tperiph_br_tire_temps[4] = t.TPERIPH_BR_TIRETEMP_5;
                vsm_state.tperiph_br_tire_temps[5] = t.TPERIPH_BR_TIRETEMP_6;
                vsm_state.tperiph_br_tire_temps[6] = t.TPERIPH_BR_TIRETEMP_7;
                vsm_state.tperiph_br_tire_temps[7] = t.TPERIPH_BR_TIRETEMP_8;
            }
            // Battery module voltages (raw byte, display formula handles 2V offset)
            else if (msg.id == 0x494) {
                auto& m = g_dbcc_state.can_0x494_BATT_TPDO_MOD0_VOLTS;
                vsm_state.batt_mod_volts[0][0] = m.BATT_MOD0_VOLTS_CELL0;
                vsm_state.batt_mod_volts[0][1] = m.BATT_MOD0_VOLTS_CELL1;
                vsm_state.batt_mod_volts[0][2] = m.BATT_MOD0_VOLTS_CELL2;
                vsm_state.batt_mod_volts[0][3] = m.BATT_MOD0_VOLTS_CELL3;
                vsm_state.batt_mod_volts[0][4] = m.BATT_MOD0_VOLTS_CELL4;
                vsm_state.batt_mod_volts[0][5] = m.BATT_MOD0_VOLTS_CELL5;
            } else if (msg.id == 0x497) {
                auto& m = g_dbcc_state.can_0x497_BATT_TPDO_MOD1_VOLTS;
                vsm_state.batt_mod_volts[1][0] = m.BATT_MOD0_VOLTS_CELL0;
                vsm_state.batt_mod_volts[1][1] = m.BATT_MOD0_VOLTS_CELL1;
                vsm_state.batt_mod_volts[1][2] = m.BATT_MOD0_VOLTS_CELL2;
                vsm_state.batt_mod_volts[1][3] = m.BATT_MOD0_VOLTS_CELL3;
                vsm_state.batt_mod_volts[1][4] = m.BATT_MOD0_VOLTS_CELL4;
                vsm_state.batt_mod_volts[1][5] = m.BATT_MOD0_VOLTS_CELL5;
            } else if (msg.id == 0x49a) {
                auto& m = g_dbcc_state.can_0x49a_BATT_TPDO_MOD2_VOLTS;
                vsm_state.batt_mod_volts[2][0] = m.BATT_MOD0_VOLTS_CELL0;
                vsm_state.batt_mod_volts[2][1] = m.BATT_MOD0_VOLTS_CELL1;
                vsm_state.batt_mod_volts[2][2] = m.BATT_MOD0_VOLTS_CELL2;
                vsm_state.batt_mod_volts[2][3] = m.BATT_MOD0_VOLTS_CELL3;
                vsm_state.batt_mod_volts[2][4] = m.BATT_MOD0_VOLTS_CELL4;
                vsm_state.batt_mod_volts[2][5] = m.BATT_MOD0_VOLTS_CELL5;
            } else if (msg.id == 0x49d) {
                auto& m = g_dbcc_state.can_0x49d_BATT_TPDO_MOD3_VOLTS;
                vsm_state.batt_mod_volts[3][0] = m.BATT_MOD0_VOLTS_CELL0;
                vsm_state.batt_mod_volts[3][1] = m.BATT_MOD0_VOLTS_CELL1;
                vsm_state.batt_mod_volts[3][2] = m.BATT_MOD0_VOLTS_CELL2;
                vsm_state.batt_mod_volts[3][3] = m.BATT_MOD0_VOLTS_CELL3;
                vsm_state.batt_mod_volts[3][4] = m.BATT_MOD0_VOLTS_CELL4;
                vsm_state.batt_mod_volts[3][5] = m.BATT_MOD0_VOLTS_CELL5;
            } else if (msg.id == 0x4a0) {
                auto& m = g_dbcc_state.can_0x4a0_BATT_TPDO_MOD4_VOLTS;
                vsm_state.batt_mod_volts[4][0] = m.BATT_MOD0_VOLTS_CELL0;
                vsm_state.batt_mod_volts[4][1] = m.BATT_MOD0_VOLTS_CELL1;
                vsm_state.batt_mod_volts[4][2] = m.BATT_MOD0_VOLTS_CELL2;
                vsm_state.batt_mod_volts[4][3] = m.BATT_MOD0_VOLTS_CELL3;
                vsm_state.batt_mod_volts[4][4] = m.BATT_MOD0_VOLTS_CELL4;
                vsm_state.batt_mod_volts[4][5] = m.BATT_MOD0_VOLTS_CELL5;
            }
            // Battery module temps (raw * 0.25 scaling, divide by 4 for °C, TEMPS_A only)
            else if (msg.id == 0x495) {
                auto& m = g_dbcc_state.can_0x495_BATT_TPDO_MOD0_TEMPS_A;
                vsm_state.batt_mod_temps_A[0][0] = m.BATT_MOD0_TEMPS_CELL0 / 4;
                vsm_state.batt_mod_temps_A[0][1] = m.BATT_MOD0_TEMPS_CELL1 / 4;
                vsm_state.batt_mod_temps_A[0][2] = m.BATT_MOD0_TEMPS_CELL2 / 4;
                vsm_state.batt_mod_temps_A[0][3] = m.BATT_MOD0_TEMPS_CELL3 / 4;
                vsm_state.batt_mod_temps_A[0][4] = m.BATT_MOD0_TEMPS_CELL4 / 4;
                vsm_state.batt_mod_temps_A[0][5] = m.BATT_MOD0_TEMPS_CELL5 / 4;
            } else if (msg.id == 0x498) {
                auto& m = g_dbcc_state.can_0x498_BATT_TPDO_MOD1_TEMPS_A;
                vsm_state.batt_mod_temps_A[1][0] = m.BATT_MOD0_TEMPS_CELL0 / 4;
                vsm_state.batt_mod_temps_A[1][1] = m.BATT_MOD0_TEMPS_CELL1 / 4;
                vsm_state.batt_mod_temps_A[1][2] = m.BATT_MOD0_TEMPS_CELL2 / 4;
                vsm_state.batt_mod_temps_A[1][3] = m.BATT_MOD0_TEMPS_CELL3 / 4;
                vsm_state.batt_mod_temps_A[1][4] = m.BATT_MOD0_TEMPS_CELL4 / 4;
                vsm_state.batt_mod_temps_A[1][5] = m.BATT_MOD0_TEMPS_CELL5 / 4;
            } else if (msg.id == 0x49b) {
                auto& m = g_dbcc_state.can_0x49b_BATT_TPDO_MOD2_TEMPS_A;
                vsm_state.batt_mod_temps_A[2][0] = m.BATT_MOD0_TEMPS_CELL0 / 4;
                vsm_state.batt_mod_temps_A[2][1] = m.BATT_MOD0_TEMPS_CELL1 / 4;
                vsm_state.batt_mod_temps_A[2][2] = m.BATT_MOD0_TEMPS_CELL2 / 4;
                vsm_state.batt_mod_temps_A[2][3] = m.BATT_MOD0_TEMPS_CELL3 / 4;
                vsm_state.batt_mod_temps_A[2][4] = m.BATT_MOD0_TEMPS_CELL4 / 4;
                vsm_state.batt_mod_temps_A[2][5] = m.BATT_MOD0_TEMPS_CELL5 / 4;
            } else if (msg.id == 0x49e) {
                auto& m = g_dbcc_state.can_0x49e_BATT_TPDO_MOD3_TEMPS_A;
                vsm_state.batt_mod_temps_A[3][0] = m.BATT_MOD0_TEMPS_CELL0 / 4;
                vsm_state.batt_mod_temps_A[3][1] = m.BATT_MOD0_TEMPS_CELL1 / 4;
                vsm_state.batt_mod_temps_A[3][2] = m.BATT_MOD0_TEMPS_CELL2 / 4;
                vsm_state.batt_mod_temps_A[3][3] = m.BATT_MOD0_TEMPS_CELL3 / 4;
                vsm_state.batt_mod_temps_A[3][4] = m.BATT_MOD0_TEMPS_CELL4 / 4;
                vsm_state.batt_mod_temps_A[3][5] = m.BATT_MOD0_TEMPS_CELL5 / 4;
            } else if (msg.id == 0x4a1) {
                auto& m = g_dbcc_state.can_0x4a1_BATT_TPDO_MOD4_TEMPS_A;
                vsm_state.batt_mod_temps_A[4][0] = m.BATT_MOD0_TEMPS_CELL0 / 4;
                vsm_state.batt_mod_temps_A[4][1] = m.BATT_MOD0_TEMPS_CELL1 / 4;
                vsm_state.batt_mod_temps_A[4][2] = m.BATT_MOD0_TEMPS_CELL2 / 4;
                vsm_state.batt_mod_temps_A[4][3] = m.BATT_MOD0_TEMPS_CELL3 / 4;
                vsm_state.batt_mod_temps_A[4][4] = m.BATT_MOD0_TEMPS_CELL4 / 4;
                vsm_state.batt_mod_temps_A[4][5] = m.BATT_MOD0_TEMPS_CELL5 / 4;
            }
            // Battery module temps (raw * 0.25 scaling, divide by 4 for °C, TEMPS_B only)
            else if (msg.id == 0x496) {
                auto& m = g_dbcc_state.can_0x496_BATT_TPDO_MOD0_TEMPS_B;
                vsm_state.batt_mod_temps_B[0][0] = m.BATT_MOD0_TEMPS_CELL6 / 4;
                vsm_state.batt_mod_temps_B[0][1] = m.BATT_MOD0_TEMPS_CELL7 / 4;
                vsm_state.batt_mod_temps_B[0][2] = m.BATT_MOD0_TEMPS_CELL8 / 4;
                vsm_state.batt_mod_temps_B[0][3] = m.BATT_MOD0_TEMPS_CELL9 / 4;
                vsm_state.batt_mod_temps_B[0][4] = m.BATT_MOD0_TEMPS_CELL10 / 4;
                vsm_state.batt_mod_temps_B[0][5] = m.BATT_MOD0_TEMPS_CELL11 / 4;
            } else if (msg.id == 0x499) {
                auto& m = g_dbcc_state.can_0x499_BATT_TPDO_MOD1_TEMPS_B;
                vsm_state.batt_mod_temps_B[1][0] = m.BATT_MOD0_TEMPS_CELL6 / 4;
                vsm_state.batt_mod_temps_B[1][1] = m.BATT_MOD0_TEMPS_CELL7 / 4;
                vsm_state.batt_mod_temps_B[1][2] = m.BATT_MOD0_TEMPS_CELL8 / 4;
                vsm_state.batt_mod_temps_B[1][3] = m.BATT_MOD0_TEMPS_CELL9 / 4;
                vsm_state.batt_mod_temps_B[1][4] = m.BATT_MOD0_TEMPS_CELL10 / 4;
                vsm_state.batt_mod_temps_B[1][5] = m.BATT_MOD0_TEMPS_CELL11 / 4;
            } else if (msg.id == 0x49c) {
                auto& m = g_dbcc_state.can_0x49c_BATT_TPDO_MOD2_TEMPS_B;
                vsm_state.batt_mod_temps_B[2][0] = m.BATT_MOD0_TEMPS_CELL6 / 4;
                vsm_state.batt_mod_temps_B[2][1] = m.BATT_MOD0_TEMPS_CELL7 / 4;
                vsm_state.batt_mod_temps_B[2][2] = m.BATT_MOD0_TEMPS_CELL8 / 4;
                vsm_state.batt_mod_temps_B[2][3] = m.BATT_MOD0_TEMPS_CELL9 / 4;
                vsm_state.batt_mod_temps_B[2][4] = m.BATT_MOD0_TEMPS_CELL10 / 4;
                vsm_state.batt_mod_temps_B[2][5] = m.BATT_MOD0_TEMPS_CELL11 / 4;
            } else if (msg.id == 0x49f) {
                auto& m = g_dbcc_state.can_0x49f_BATT_TPDO_MOD3_TEMPS_B;
                vsm_state.batt_mod_temps_B[3][0] = m.BATT_MOD0_TEMPS_CELL6 / 4;
                vsm_state.batt_mod_temps_B[3][1] = m.BATT_MOD0_TEMPS_CELL7 / 4;
                vsm_state.batt_mod_temps_B[3][2] = m.BATT_MOD0_TEMPS_CELL8 / 4;
                vsm_state.batt_mod_temps_B[3][3] = m.BATT_MOD0_TEMPS_CELL9 / 4;
                vsm_state.batt_mod_temps_B[3][4] = m.BATT_MOD0_TEMPS_CELL10 / 4;
                vsm_state.batt_mod_temps_B[3][5] = m.BATT_MOD0_TEMPS_CELL11 / 4;
            } else if (msg.id == 0x4a2) {
                auto& m = g_dbcc_state.can_0x4a2_BATT_TPDO_MOD4_TEMPS_B;
                vsm_state.batt_mod_temps_B[4][0] = m.BATT_MOD0_TEMPS_CELL6 / 4;
                vsm_state.batt_mod_temps_B[4][1] = m.BATT_MOD0_TEMPS_CELL7 / 4;
                vsm_state.batt_mod_temps_B[4][2] = m.BATT_MOD0_TEMPS_CELL8 / 4;
                vsm_state.batt_mod_temps_B[4][3] = m.BATT_MOD0_TEMPS_CELL9 / 4;
                vsm_state.batt_mod_temps_B[4][4] = m.BATT_MOD0_TEMPS_CELL10 / 4;
                vsm_state.batt_mod_temps_B[4][5] = m.BATT_MOD0_TEMPS_CELL11 / 4;
            }
            // IZZE brake disc temps: raw * 0.1 - 100 = C
            // CH assignment: CH1=FL, CH5=FR, CH9=RL, CH13=RR (NOT SURE ABOUT THIS)
            else if (msg.id == 0x4c4) {
                vsm_state.izze_brake_fl = g_dbcc_state.can_0x4c4_IZZE_BRAKETEMP_S1M1.IZZE_BRAKETEMP_S1_CH1 * 0.1f - 100.0f;
            } else if (msg.id == 0x4c5) {
                vsm_state.izze_brake_fr = g_dbcc_state.can_0x4c5_IZZE_BRAKETEMP_S1M2.IZZE_BRAKETEMP_S1_CH5 * 0.1f - 100.0f;
            } else if (msg.id == 0x4c6) {
                vsm_state.izze_brake_rl = g_dbcc_state.can_0x4c6_IZZE_BRAKETEMP_S1M3.IZZE_BRAKETEMP_S1_CH9 * 0.1f - 100.0f;
            } else if (msg.id == 0x4c7) {
                vsm_state.izze_brake_rr = g_dbcc_state.can_0x4c7_IZZE_BRAKETEMP_S1M4.IZZE_BRAKETEMP_S1_CH13 * 0.1f - 100.0f;
            }
            break;
        }
        default:
            break;
        }
    } // while (can.read(msg))
}

/**
 * @brief Sends the Drive, Traction, and Regen Modes CAN message
 *
 */
void sendCANMessage() {
    // Manual Bit packing
    uint8_t steering_data[] = {
        static_cast<uint8_t>(
            (driveState) |         // bits 0-1
            (tractionState << 2) | // bits 2-3
            (regenState << 4)      // bits 4-5
        )
    };

    CANMessage steering_msg{0x378u, steering_data, 1};
    // can.write(steering_msg);
}

/**
 *  Called once every second
 */
void readFPS(){
    curFrame = screen.readFrames();
    fps = curFrame-lastFrame;
    lastFrame = curFrame;
    printf("fps: %d", fps);
}
