#include "BT817Q.hpp"
#include "dash_screen.hpp"
#include "..\libraries\FilterUtils\include\debounced_digital_in.h"
#include "mbed.h"
#include "pin_config.hpp"
#include "fs4can.h"

DashScreen screen{
    PIN_MOSI, PIN_MISO, PIN_SCK, PIN_CS, PIN_PDN, PIN_IRQ, EvePresets::CFAF800480H0
};
CAN can{PIN_CAN_RX, PIN_CAN_TX, CAN_FREQUENCY};
CANMessage msg;
//BUTTONS: Layout, Lap, Launch
    //Lap and Launch Don't seem to be connected to the MCU and go into some other connector
    //Might not need to do debouncing since it looks like there is an RC low-pass filter
    //Could just use an interurptIn if not
DigitalIn layoutBtn{PIN_LAYOUT};
DebouncedDigitalIn debouncedLayoutBtn{layoutBtn,5};
uint8_t currentScreen = 0; 
EventQueue queue = EventQueue{EVENTS_EVENT_SIZE * 32};

bool lastLayoutBtnState;
//  SWITCHES: Drive, Traction, Regen mode
//  Probably want to just read the voltage from each switch to determine what mode should be outputed
//  Don't know if there's any specific order to determine what mode 
//  methink

// CAN message structure generated by cantools
// The file is like 20k lines and I'm not sure if I should push that to the repo
struct fs4can_batt_tpdo_status_t g_batt_tpdo_status;

int main() {
    printf("Hello World!!\n");
    screen.init(EvePresets::CFAF800480H0);
    debouncedLayoutBtn.set_valid_read_count(7);
    can.attach(&canISR, CAN::RxIrq); //callback function to handle can interrupts
    queue.call_every(10ms, &readLayoutButton);
    queue.call_every(10ms, &drawScreenLayout);
    queue.dispatch_forever();
    return 0;
    // Todo - read CAN, decode relevant data, render screen
    
    // Todo - read switch and button positions
}

/**
 * @brief Function to read button state and cycles through possible layouts on button press
 * These are the what values correspond to what screen
 * 0: main
 * 1: Thermal
 * 2: CellTemps
 * 3: CellVolts
 * 4: Fault
 */
void readLayoutButton(){
    const bool debounced_button_state = debouncedLayoutBtn.read();
    if(debounced_button_state && !lastLayoutBtnState)
    {
        currentScreen = (currentScreen>=4)?0:(currentScreen+1);
    }
    lastLayoutBtnState = debounced_button_state;
}

/**
 * @brief Function to draw screen layout
 * Layouts depend on currentScreen
 * 0: main
 * 1: Thermal
 * 2: CellTemps
 * 3: CellVolts
 * 4: Fault
 */
void drawScreenLayout()
{
        //Render the screen like how it was done before?
        //Should look into optimal ways of doing this
        //Also add fps overlay to the screens

    switch(currentScreen){
        case 0:
            screen.drawMainDisplay(
                    //Should I use vsm state
                    //Currently not sure if I should organize the info from CAN into a struct like the vsm from FS3 since the screens only display like 30 different values
                    vsm_state.accStatus.SHUTDOWN_STATE, 
                    vsm_state.smeTemp.FAULT_LEVEL, 
                    vsm_state.etcStatus.RTD, 
                    vsm_state.accStatus.PRECHARGE_DONE, 
                    true /*fans*/, 
                    vsm_state.accPower.PACK_VOLTAGE, 
                    max_temp, 
                    vsm_state.accPower.SOC, 
                    n,
                    vsm_state.vdmGpsData.SPEED, 
                    vsm.getLapTime(), 
                    vsm_state.accStatus.GLV_VOLTAGE, 
                    vsm_state.smeTemp.MOTOR_TEMP, 
                    vsm_state.smeTemp.CONTROLLER_TEMP,
                    vsm_state.smeTemp.DC_BUS_V
            );
            break;
        case 1:
            screen.drawThermalScreen();
            break;
        case 2:
            screen.drawTempCell();
        case 3:
            screen.drawVoltCell();
        case 4:
            screen.drawDebugFaultLayout();
        
    }
}
/**
 * @brief Called an incomming CAN message from interrupt
 *  Just adds the decoding process to the queue
 */
void canISR()
{
    queue.call(processCANMessage);
}
/**
 * @brief Decoding the CAN message receieved
 * Worried about if the eventQueue is busy with other tasks and the original message is missed
 * Not sure how long the other tasks take and the maximum time between messages
 * Might want to move the decoding to an interrupt but this is just for displaying data so I think it's fine
 */
void processCANMessage()
{
    if(can.read(msg))
    {
        switch(msg.id){
            //Reading CAN 
            //Wow this is going to be a lot of can message reading
            //Might want to just do this in a seperate class
            //Wonder if I can just yoink the VehicleStateManager from FS3
            //Seems like there might be a script to generate this
            //I'm seeing some scary things happenening in the VSM

            //BATTERY MESSAGES
            // Currently using a c file generated by cantools
            // seems fine but I wonder if there's any specific reason why we don't use this
            // Should I use virtual ICAN functions instead for testing?
            case FS4CAN_BATT_TPDO_STATUS_FRAME_ID:
                fs4can_batt_tpdo_status_unpack(&g_batt_tpdo_status, msg.data, msg.len);
                bool bms_fault = fs4can_batt_tpdo_status_batt_status_glv_voltage_decode(g_batt_tpdo_status.batt_status_bms_fault);
                bool ims_fault = fs4can_batt_tpdo_status_batt_status_imd_fault_decode(g_batt_tpdo_status.batt_status_imd_fault);
                break;
            default:
                break;
        }
    }
}

void sendCANMessage(){
    //Send the CAN Message
    //Expecting Drive, Traction, and Regen Modes from dials
}