#include "BT817Q.hpp"
#include "dash_screen.hpp"
#include "..\libraries\FilterUtils\include\debounced_digital_in.h"
#include "mbed.h"
#include "pin_config.hpp"
#include "fs4can.h"

DashScreen screen{
    PIN_MOSI, PIN_MISO, PIN_SCK, PIN_CS, PIN_PDN, PIN_IRQ, EvePresets::CFAF800480H0
};
CAN can{PIN_CAN_RX, PIN_CAN_TX, CAN_FREQUENCY};
CANMessage msg;
//BUTTONS: Layout, Lap, Launch
    //Lap and Launch doesn't seem to be managed by the MCU
DigitalIn layoutBtn{PIN_LAYOUT};
DebouncedDigitalIn debouncedLayoutBtn{layoutBtn,5};
uint8_t currentScreen = 0; 
EventQueue queue = EventQueue{EVENTS_EVENT_SIZE * 32};

bool lastLayoutBtnState;
//  DIALS: Drive, Traction, Regen mode
AnalogIn driveDial{PIN_MODE};
AnalogIn tractionDial{PIN_TC};
AnalogIn regenDial{PIN_REGEN};

uint8_t driveState;
uint8_t tractionState;
uint8_t regenState;

// CAN message structure generated by dbcc
// dbcc {dbcFileName.dbc}
// Also used a python function to generate the decoding stuff
// Our dbc file is a bit weird, the extended CAN id's need to have a 1 in the MSB
// These Need to Come after BO
    // BA_DEF_ "BusType" STRING ;
    // BA_DEF_DEF_ "BusType" "";
    // BA_ "BusType" "CAN";
struct VehicleState{
    uint8_t batt_status_shutdown_final;
    uint8_t batt_power_soc;
    uint8_t batt_status_bms_fault;
    uint8_t batt_status_imd_fault;
    uint8_t batt_status_shutdown_out;  //Two Shutdowns wonder which to use
    uint8_t batt_status_precharge_done; 
    uint8_t batt_status_precharging; 
    uint8_t batt_status_charging; 
    uint16_t batt_power_pack_voltage; 
    uint16_t batt_status_glv_voltage;
    uint32_t batt_status_fault_index; 
    uint16_t sme_temp_dc_bus_v;
    uint8_t sme_temp_controllertemperature;
    uint8_t sme_trqspd_controller_overtermp; 
    uint8_t sme_trqspd_running; 
    uint8_t sme_trqspd_powering_enabled; 
    uint8_t sme_trqspd_powering_ready; 
    uint8_t sme_temp_motortemperature; 
    uint8_t sme_temp_faultcode; 
    uint8_t sme_temp_faultlevel; 
    uint8_t vcu_etc_ready_to_drive; 
    uint8_t vcu_etc_batt_precharge_done;
    uint8_t vcu_etc_brake_pedal_travel; 
    uint8_t vcu_etc_bpps_he;
    uint8_t vcu_etc_implausibility_apps_out_of_range;
    uint8_t vcu_etc_implausibility_bpps_out_of_range;
    uint8_t vcu_etc_implausibility_apps_deviation;
    uint8_t vcu_etc_implausibility_bse_out_of_range;
    uint8_t vcu_etc_implausibility_brake_and_accel;
    uint16_t vdm_gps_speed;

};
can_obj_fs4can_h_t g_dbcc_state;
VehicleState vsm_state;

int main() {
    printf("Hello World!!\n");
    screen.init(EvePresets::CFAF800480H0);
    debouncedLayoutBtn.set_valid_read_count(7);
    can.attach(&canISR, CAN::RxIrq); //callback function to handle can interrupts
    queue.call_every(10ms, &readLayoutButton);
    queue.call_everu(10ms, &readDials);
    queue.call_every(10ms, &drawScreenLayout);
    queue.dispatch_forever();
    return 0;
    // Todo - read CAN, decode relevant data, render screen
    
    // Todo - read switch and button positions
}

/**
 * @brief Function to read button state and cycles through possible layouts on button press
 * These are the what values correspond to what screen
 */
void readLayoutButton(){
    const bool debounced_button_state = debouncedLayoutBtn.read();
    if(debounced_button_state && !lastLayoutBtnState)
    {
        currentScreen = (currentScreen>=4)?0:(currentScreen+1);
    }
    lastLayoutBtnState = debounced_button_state;
}

/**
 * @brief Function to read dial state
 *  3.3V, 2.2V, 1.1V, GND
 *  Not sure how jiterry these readings
 *  I can compare floats or just cast it to an int 
 */
void readDials(){
    //0 - 3.3V 
    //0 - 4096, each volt is 1241
    //ADC is 12 Bits ADC12_IN1
    uint16_t rawDriveVal = driveDial.read_u16() >> 4;
    if(rawDriveVal >= 3351) driveState = 2; // > 2.7V
    else if(rawDriveVal >= 2110) driveState = 1; // > 1.7V
    else if(rawDriveVal >= 744) driveState = 0; // > 0.6V
    else driveState = 0; //ground, idk what to do here

    uint16_t rawTractionVal = tractionDial.read_u16() >> 4;
    if(rawTractionVal >= 3351) tractionState = 2; // > 2.7V
    else if(rawTractionVal >= 2110) tractionState = 1; // > 1.7V
    else if(rawTractionVal >= 744) tractionState = 0; // > 0.6V
    else tractionState = 0; //ground

    uint16_t rawRegenVal = regenDial.read_u16() >> 4;
    if(rawRegenVal >= 3351) regenState = 2; // > 2.7V
    else if(rawRegenVal >= 2110) regenState = 1; // > 1.7V
    else if(rawRegenVal >= 744) regenState = 0; // > 0.6V
    else regenState = 0; //ground

    //Send the CAN Message
    sendCANMessage();
}
/**
 * @brief Function to draw screen layout
 * Layouts depend on currentScreen
 * 0: main
 * 1: Thermal
 * 2: CellTemps
 * 3: CellVolts
 * 4: Fault
 */
void drawScreenLayout()
{
        //Render the screen like how it was done before?
        //Should look into optimal ways of doing this
        //Also add fps overlay to the screens

    switch(currentScreen){
        case 0:
            screen.drawMainDisplay(
                    vsm_state.batt_status_shutdown_final, //Three different options now
                    vsm_state.batt_status_fault_index,  //not sure
                    vsm_state.vcu_etc_ready_to_drive, 
                    vsm_state.vcu_etc_batt_precharge_done, 
                    true /*fans*/, 
                    vsm_state.batt_power_pack_voltage, 
                    1, //acc_temp
                    vsm_state.batt_power_soc, 
                    1, //ticks
                    vsm_state.vdm_gps_speed, 
                    "lap", //laptime
                    vsm_state.batt_status_glv_voltage, 
                    vsm_state.sme_temp_motortemperature, 
                    vsm_state.sme_temp_controllertemperature,
                    vsm_state.sme_temp_dc_bus_v
            );
            break;
        case 1:
            // screen.drawThermalScreen(
            //     uint8_t acc_temp, //acc_temp? Maybe take the average of battery modules
            //     uint8_t vsm_state.sme_temp_motortemperature, 
            //     uint8_t vsm_state.sme_temp_controllertemperature, 
            //     float fl_surface,  //Confused why TireTemp in the dbc is 8 bytes and not 1? 
            //     float fl_side,      //Should check if previous dbc also has 8 byte tire temps
            //     float fr_surface, 
            //     float fr_side,     
            //     float rl_surface, 
            //     float rl_side, 
            //     float rr_surface, 
            //     float rr_side, 
            //     float brake_fl,  //I only see 5 brake temps on the dbc
            //     float brake_fr,  //What does S1M1, S1M2, or CH mean?
            //     float brake_rl, 
            //     float brake_rr, 
            //     float brake_f, 
            //     float brake_r
            // );
            break;
        case 2:
            screen.debugCellTemps({}); //Uhh, each Battery module has 6 segments
        case 3:
            screen.debugCellVolts({}); //idk
        case 4:
            screen.drawDebugFaultLayout(
                 vsm_state.batt_status_bms_fault, 
                 vsm_state.batt_status_imd_fault, 
                 vsm_state.batt_status_shutdown_out,  //Two Shutdowns
                 vsm_state.batt_status_precharge_done, 
                 vsm_state.batt_status_precharging, 
                 vsm_state.batt_status_charging, 
                 vsm_state.batt_power_pack_voltage, 
                 vsm_state.batt_status_glv_voltage, 
                 vsm_state.batt_status_fault_index, 
                 vsm_state.vcu_etc_ready_to_drive, 
                 (vsm_state.vcu_etc_implausibility_apps_out_of_range|vsm_state.vcu_etc_implausibility_bpps_out_of_range|vsm_state.vcu_etc_implausibility_apps_deviation|vsm_state.vcu_etc_implausibility_bse_out_of_range|vsm_state.vcu_etc_implausibility_brake_and_accel), //lot of implausbility options now
                 vsm_state.vcu_etc_batt_precharge_done,
                 vsm_state.vcu_etc_brake_pedal_travel, 
                 vsm_state.vcu_etc_bpps_he,
                 vsm_state.sme_trqspd_controller_overtermp, 
                 vsm_state.sme_trqspd_running, 
                 vsm_state.sme_trqspd_powering_enabled, 
                 vsm_state.sme_trqspd_powering_ready, 
                 vsm_state.sme_temp_motortemperature, 
                 vsm_state.sme_temp_faultcode, 
                 vsm_state.sme_temp_faultlevel, 
                 1 // tick
            );
        
    }
}
/**
 * @brief Called when there is an incomming CAN message from interrupt
 *  Just adds the decoding process to the queue
 */
void canISR()
{
    queue.call(processCANMessage);
}
/**
 * @brief Decoding the CAN message receieved
 * Worried about if the eventQueue is busy with other tasks and the original message is missed
 * Not sure how long the other tasks take and the maximum time between messages
 * Might want to move the decoding to an interrupt but this is just for displaying data so I think it's fine
 */
//wivsMnnmM4Q
void processCANMessage()
{
    switch (msg.id) {
        case 0x189: // VCU_TPDO_ETC_STATUS_1
        case 0x18a: // VCU_TPDO_ETC_STATUS_2
        case 0x482: // SME_TPDO_Torque_speed
        case 0x682: // SME_TPDO_Temperature
        case 0x188: // BATT_TPDO_STATUS
        case 0x288: // BATT_TPDO_POWER
        case 0xa0001: // VDM_GPS_DATA
        {
            // 1. Convert Mbed uint8_t[8] to dbcc uint64_t
            // Since STM32 is Little-Endian, memcpy puts byte[0] into the LSB perfectly
            uint64_t payload = 0;
            memcpy(&payload, msg.data, msg.len);
            //This doesn't really need to happen but its safe
            // 2. Call the dbcc master unpacker
            unpack_message(&g_dbcc_state, msg.id, payload, msg.len, 0);

            // 3. Extract the decoded values to your dashboard state
            if (false) {} // Setup for if/else block
            else if (msg.id == 0x189) {
                // vsm_state.vcu_etc_apps1_he = g_dbcc_state.can_0x189_VCU_TPDO_ETC_STATUS_1.VCU_ETC_APPS1_HE;
                // vsm_state.vcu_etc_apps2_he = g_dbcc_state.can_0x189_VCU_TPDO_ETC_STATUS_1.VCU_ETC_APPS2_HE;
                vsm_state.vcu_etc_bpps_he = g_dbcc_state.can_0x189_VCU_TPDO_ETC_STATUS_1.VCU_ETC_BPPS_HE;
                // vsm_state.vcu_etc_accel_pedal_travel = g_dbcc_state.can_0x189_VCU_TPDO_ETC_STATUS_1.VCU_ETC_ACCEL_PEDAL_TRAVEL;
                vsm_state.vcu_etc_brake_pedal_travel = g_dbcc_state.can_0x189_VCU_TPDO_ETC_STATUS_1.VCU_ETC_BRAKE_PEDAL_TRAVEL;
            }
            else if (msg.id == 0x18a) {
                // vsm_state.vcu_etc_brake_presssure_front = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_BRAKE_PRESSSURE_FRONT;
                // vsm_state.vcu_etc_brake_presssure_rear = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_BRAKE_PRESSSURE_REAR;
                vsm_state.vcu_etc_ready_to_drive = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_READY_TO_DRIVE;
                // vsm_state.vcu_etc_motor_enabled = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_MOTOR_ENABLED;
                // vsm_state.vcu_etc_rtd_button_pressed = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_RTD_BUTTON_PRESSED;
                vsm_state.vcu_etc_batt_precharge_done = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_BATT_PRECHARGE_DONE;
                vsm_state.vcu_etc_implausibility_apps_out_of_range = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_IMPLAUSIBILITY_APPS_OUT_OF_RANGE;
                vsm_state.vcu_etc_implausibility_bpps_out_of_range = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_IMPLAUSIBILITY_BPPS_OUT_OF_RANGE;
                vsm_state.vcu_etc_implausibility_apps_deviation = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_IMPLAUSIBILITY_APPS_DEVIATION;
                vsm_state.vcu_etc_implausibility_bse_out_of_range = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_IMPLAUSIBILITY_BSE_OUT_OF_RANGE;
                vsm_state.vcu_etc_implausibility_brake_and_accel = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_IMPLAUSIBILITY_BRAKE_AND_ACCEL;
                // vsm_state.vcu_etc_reverse = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_REVERSE;
                // vsm_state.vcu_etc_brakelight = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_BRAKELIGHT;
                // vsm_state.vcu_etc_can_regen = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_CAN_REGEN;
                // vsm_state.vcu_etc_must_use_hydraulic_brakes = g_dbcc_state.can_0x18a_VCU_TPDO_ETC_STATUS_2.VCU_ETC_MUST_USE_HYDRAULIC_BRAKES;
            }
            else if (msg.id == 0x482) {
                // vsm_state.sme_trqspd_speed = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Speed;
                // vsm_state.sme_trqspd_torque = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Torque;
                // vsm_state.sme_trqspd_soc_low_traction = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_SOC_Low_Traction;
                // vsm_state.sme_trqspd_soc_low_hydraulic = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_SOC_Low_Hydraulic;
                // vsm_state.sme_trqspd_reverse = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Reverse;
                // vsm_state.sme_trqspd_forward = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Forward;
                // vsm_state.sme_trqspd_park_brake = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Park_Brake;
                // vsm_state.sme_trqspd_pedal_brake = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Pedal_Brake;
                vsm_state.sme_trqspd_controller_overtermp = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Controller_Overtermp;
                // vsm_state.sme_trqspd_key_switch_overvolt = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Key_Switch_Overvolt;
                // vsm_state.sme_trqspd_key_switch_undervolt = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Key_Switch_Undervolt;
                vsm_state.sme_trqspd_running = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Running;
                // vsm_state.sme_trqspd_traction = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Traction;
                // vsm_state.sme_trqspd_hydraulic = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Hydraulic;
                vsm_state.sme_trqspd_powering_enabled = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Powering_Enabled;
                vsm_state.sme_trqspd_powering_ready = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Powering_Ready;
                // vsm_state.sme_trqspd_precharging = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_Precharging;
                // vsm_state.sme_trqspd_contactor_closed = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_contactor_closed;
                // vsm_state.sme_trqspd_motorflags = g_dbcc_state.can_0x482_SME_TPDO_Torque_speed.SME_TRQSPD_MotorFlags;
            }
            else if (msg.id == 0x682) {
                vsm_state.sme_temp_motortemperature = g_dbcc_state.can_0x682_SME_TPDO_Temperature.SME_TEMP_MotorTemperature;
                vsm_state.sme_temp_controllertemperature = g_dbcc_state.can_0x682_SME_TPDO_Temperature.SME_TEMP_ControllerTemperature;
                vsm_state.sme_temp_dc_bus_v = g_dbcc_state.can_0x682_SME_TPDO_Temperature.SME_TEMP_DC_Bus_V;
                vsm_state.sme_temp_faultcode = g_dbcc_state.can_0x682_SME_TPDO_Temperature.SME_TEMP_FaultCode;
                vsm_state.sme_temp_faultlevel = g_dbcc_state.can_0x682_SME_TPDO_Temperature.SME_TEMP_FaultLevel;
                // vsm_state.sme_temp_buscurrent = g_dbcc_state.can_0x682_SME_TPDO_Temperature.SME_TEMP_BusCurrent;
            }
            else if (msg.id == 0x188) {
                vsm_state.batt_status_bms_fault = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_BMS_FAULT;
                vsm_state.batt_status_imd_fault = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_IMD_FAULT;
                vsm_state.batt_status_shutdown_final = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_SHUTDOWN_FINAL;
                // vsm_state.batt_status_shutdown_in = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_SHUTDOWN_IN;
                vsm_state.batt_status_shutdown_out = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_SHUTDOWN_OUT;
                vsm_state.batt_status_precharging = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_PRECHARGING;
                vsm_state.batt_status_precharge_done = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_PRECHARGE_DONE;
                vsm_state.batt_status_charging = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_CHARGING;
                // vsm_state.batt_status_balancing = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_BALANCING;
                // vsm_state.batt_status_cell_voltage_too_low = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_CELL_VOLTAGE_TOO_LOW;
                // vsm_state.batt_status_cell_voltage_too_high = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_CELL_VOLTAGE_TOO_HIGH;
                // vsm_state.batt_status_pack_temp_too_low = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_PACK_TEMP_TOO_LOW;
                // vsm_state.batt_status_pack_temp_too_high = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_PACK_TEMP_TOO_HIGH;
                // vsm_state.batt_status_pack_temp_too_high_crg = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_PACK_TEMP_TOO_HIGH_CRG;
                // vsm_state.batt_status_fault_module_index = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_FAULT_MODULE_INDEX;
                // vsm_state.batt_status_fault_sensor_index = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_FAULT_SENSOR_INDEX;
                vsm_state.batt_status_fault_index = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_FAULT_INDEX;
                vsm_state.batt_status_glv_voltage = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_GLV_VOLTAGE;
                // vsm_state.batt_status_fan_pwm_duty = g_dbcc_state.can_0x188_BATT_TPDO_STATUS.BATT_STATUS_FAN_PWM_DUTY;
            }
            else if (msg.id == 0x288) {
                vsm_state.batt_power_pack_voltage = g_dbcc_state.can_0x288_BATT_TPDO_POWER.BATT_POWER_PACK_VOLTAGE;
                // vsm_state.batt_power_current = g_dbcc_state.can_0x288_BATT_TPDO_POWER.BATT_POWER_CURRENT;
                // vsm_state.batt_power_instantaneous_power = g_dbcc_state.can_0x288_BATT_TPDO_POWER.BATT_POWER_INSTANTANEOUS_POWER;
                vsm_state.batt_power_soc = g_dbcc_state.can_0x288_BATT_TPDO_POWER.BATT_POWER_SOC;
            }
            else if (msg.id == 0xa0001) {
                vsm_state.vdm_gps_speed = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_SPEED;
                // vsm_state.vdm_gps_altitude = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_ALTITUDE;
                // vsm_state.vdm_gps_true_course = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_TRUE_COURSE;
                // vsm_state.vdm_gps_satellites_in_use = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_SATELLITES_IN_USE;
                // vsm_state.vdm_gps_valid1 = g_dbcc_state.can_0xa0001_VDM_GPS_DATA.VDM_GPS_VALID1;
            }
            break;
        }
        default:
            // Ignore unmapped messages
            break;
    }
}

void sendCANMessage(){
    //Send the CAN Message
    //Expecting Drive, Traction, and Regen Modes from dials
    
    //Manual Bit packing
    uint8_t steering_data[] = {
        static_cast<uint8_t>(
            (driveState) | //bits 0-1
            (tractionState << 2) | //bits 2-3
            (regenState << 4) //bits 4-5
        ) 
    };

    CANMessage steering_msg{0x378u,steering_data,1};

}