# Each target folder should contain a CMakeLists.txt which creates the
# respective CMake mbed target, eg. mbed-stm32-test-board-v1
add_subdirectory(./STM32_TEST_BOARD_V1)
add_subdirectory(./PERIPHERAL-BOARD)
add_subdirectory(./STEERING-DASH-BOARD)
add_subdirectory(./STEERING-DASH-BOARD-F4)
add_subdirectory(./TRACTIVE-BATTERY-BOARD)