# Each target folder should contain a CMakeLists.txt which creates the
# respective CMake mbed target, eg. mbed-stm32-test-board-v1
add_subdirectory(./STM32_TEST_BOARD_V1)
add_subdirectory(./peripheral-board)
add_subdirectory(./steering-dash-board)
add_subdirectory(./steering-dash-board-f4)
add_subdirectory(./tractive-battery-board)